---
#
# *** IMPORTANT NOTE ***
#
# This file is used for localhost testing. In Azerion deployments it gets replaced by ../deployment/templates/azerion-config.yml.j2.
# Any changes that should have effect in deployed environments must be made in azerion-config.yml.j2, not here.
#
status-response: "ok"
adapters:
  amx:
    enabled: true
  appnexus:
    enabled: true
  connectad:
    enabled: true
  improvedigital:
    enabled: true
  ix:
    enabled: true
  onetag:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  smartadserver:
    enabled: true
  synacormedia:
    enabled: true
  triplelift:
    enabled: true
  yieldlab:
    enabled: true
currency-converter:
  external-rates:
    enabled: true
    url: https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json
    default-timeout-ms: 40000
    refresh-period-ms: 1800000
metrics:
  prefix: pbs
cache:
  scheme: https
  host: pbc.360yield.com
  path: cache
  query: uuid=
settings:
#  default-loading-timeout: 500 # optional long value in milliseconds, default value is 500 ms
  filesystem:
    settings-filename: config/azerion-settings.yaml
    custom-settings-filename: config/azerion-custom-settings.yaml
    stored-requests-dir: stored-data/requests
    stored-imps-dir: stored-data/imps
    stored-responses-dir: stored-data/responses
gdpr:
  enabled: true
  default-value: 1
  host-vendor-id: 253
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
default-request:
  file:
    path: stored-data/requests/default.json
external-url: https://pbs-proto.360polaris.biz
google-ad-manager:
  network-code: 1015413

# Following section defines hooks to inject custom trackers in bid responses
# for /openrtb2/auction endpoint. Do not change this, if you don't know how
# hooks are implemented in PBS. As /gvast endpoint internally makes an auction
# using same code used for /openrtb2/auction handler, these hooks applies
# for /gvast endpoint as well.
# Another special note for hooks definition is hooks.host-execution-plan
# must be a valid JSON string with following structure. Converting it to
# standard YAML or breaking the JSON syntax will break the application
# bootstrapping logic and the server will not be started.
hooks:
  host-execution-plan: >
    {
      "endpoints": {
        "/openrtb2/auction": {
          "stages": {
            "entrypoint": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-entrypoint"
                    }
                  ]
                }
              ]
            },
            "processed-auction-request": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-processed-auction-request"
                    }
                  ]
                }
              ]
            },
            "processed-bidder-response": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-processed-bidder-response"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
