---
#
# *** IMPORTANT NOTE ***
#
# This file is used for localhost testing. In Azerion deployments it gets replaced by ../deployment/templates/azerion-config.yml.j2.
# Any changes that should have effect in deployed environments must be made in azerion-config.yml.j2, not here.
#
status-response: "ok"
adapters:
  appnexus:
    enabled: true
  improvedigital:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  smartadserver:
    enabled: true
  triplelift:
    enabled: true
currency-converter:
  external-rates:
    enabled: true
    url: https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json
    default-timeout-ms: 4000
    refresh-period-ms: 1800000
metrics:
  prefix: pbs
cache:
  scheme: https
  host: pbc.360yield.com
  path: cache
  query: uuid=
settings:
  default-loading-timeout: 2000
  filesystem:
    settings-filename: config/azerion-settings.yaml
    custom-settings-filename: config/azerion-custom-settings.yaml
    stored-requests-dir: stored-data/requests
    stored-imps-dir: stored-data/imps
    stored-responses-dir: stored-data/responses
gdpr:
  enabled: true
  host-vendor-id: 253
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
default-request:
  file:
    path: stored-data/requests/default.json
external-url: https://pbs-proto.360polaris.biz
google-ad-manager:
  network-code: 1015413
