---
#
# *** IMPORTANT NOTE ***
#
# This file is used for localhost testing. In Azerion deployments it gets replaced by ../deployment/templates/azerion-config.yml.j2.
# Any changes that should have effect in deployed environments must be made in azerion-config.yml.j2, not here.
#
status-response: "ok"
adapters:
  amx:
    enabled: true
  appnexus:
    enabled: true
  connectad:
    enabled: true
  improvedigital:
    enabled: true
  ix:
    enabled: true
  onetag:
    enabled: true
  openx:
    enabled: true
  pubmatic:
    enabled: true
  smartadserver:
    enabled: true
  synacormedia:
    enabled: true
  triplelift:
    enabled: true
  yieldlab:
    enabled: true
currency-converter:
  external-rates:
    enabled: true
    url: https://cdn.jsdelivr.net/gh/prebid/currency-file@1/latest.json
    default-timeout-ms: 4000
    refresh-period-ms: 1800000
metrics:
  prefix: pbs
cache:
  scheme: https
  host: pbc-proto.360polaris.biz
  path: cache
  query: uuid=
default-request:
  file:
    path : stored-data/requests/default.json
settings:
#  uncomment & edit following line, if default value needs to be changed from 500 ms
#  default-loading-timeout: 500

#  To test with http config backend in local development environment,
#  1. comment out all items in filesystem section except custom-settings-filename
#  2. uncomment http & in-memory-cache sections fully
#  3. Run `./run-mock-server.sh [debug]` command in a separate terminal/console
#     from within the <project-root>/azerion-dev-tools folder
#  4. Run PBS in another terminal
  filesystem:
    settings-filename: config/azerion-settings.yaml
    custom-settings-filename: config/azerion-custom-settings.yaml
    stored-requests-dir: stored-data/requests
    stored-imps-dir: stored-data/imps
    stored-responses-dir: stored-data/responses
    categories-dir: stored-data/categories
#  http:
#    endpoint: http://localhost:8989/config
#    amp-endpoint: http://localhost:8989/config?amp=true
#    video-endpoint: http://localhost:8989/config?video=true
#    category-endpoint: http://localhost:8989/categories
#  in-memory-cache:
#    cache-size: 10000
#    ttl-seconds: 86400 # 1 day in seconds, can be set to 1 month or more now if needed
#    notification-endpoints-enabled: true
#    http-update:
#      endpoint: http://localhost:8989/config
#      amp-endpoint: http://localhost:8989/config?amp=true
#      refresh-rate: 60000 # 1 minute in milliseconds
#      timeout: 2000 # in milliseconds

# cache invalidation endpoints
admin-endpoints:
  storedrequest:
    enabled: true
    path: /invalidate/requests
    on-application-port: true
    protected: false
  cache-invalidation:
    enabled: true
    path: /invalidate/accounts
    on-application-port: true
    protected: false

gdpr:
  enabled: false
  default-value: 1
  host-vendor-id: 253
  vendorlist:
    v1:
      cache-dir: /var/tmp/vendor1
    v2:
      cache-dir: /var/tmp/vendor2
external-url: https://pbs-proto.360polaris.biz
google-ad-manager:
  network-code: 1015413

geolocation:
  enabled: false
  type: maxmind
  maxmind:
    remote-file-syncer:
      download-url: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=6O2UlqKmfUcyXzGP&suffix=tar.gz
      save-filepath: /var/tmp/prebid/GeoLite2-City.tar.gz
      retry-count: 3
      retry-interval-ms: 3000
      timeout-ms: 300000
      update-interval-ms: 0
      http-client:
        connect-timeout-ms: 3000
        max-redirects: 3

# Following section defines hooks to inject custom trackers in bid responses
# for /openrtb2/auction endpoint. Do not change this, if you don't know how
# hooks are implemented in PBS. As /gvast endpoint internally makes an auction
# using same code used for /openrtb2/auction handler, these hooks applies
# for /gvast endpoint as well.
# Another special note for hooks definition is hooks.host-execution-plan
# must be a valid JSON string with following structure. Converting it to
# standard YAML or breaking the JSON syntax will break the application
# bootstrapping logic and the server will not be started.
hooks:
  host-execution-plan: >
    {
      "endpoints": {
        "/openrtb2/auction": {
          "stages": {
            "entrypoint": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-entrypoint"
                    }
                  ]
                }
              ]
            },
            "processed-auction-request": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-processed-auction-request"
                    }
                  ]
                }
              ]
            },
            "processed-bidder-response": {
              "groups": [
                {
                  "timeout": 5,
                  "hook-sequence": [
                    {
                      "module-code": "custom-tracker-module",
                      "hook-impl-code": "custom-tracker-processed-bidder-response"
                    }
                  ]
                }
              ]
            }
          }
        }
      }
    }
